### ISSUE TITLE
FLAME parameters from VOCA model

### ISSUE THREAD

**Issue by jzf2101** [TimoBolkart/voca#21]
I've been looking through the code and trying to figure out how to get flame parameters e.g. `shape` `pose` `camera` and `expression` out of VOCA.  It appears as if all we get out of it is the mesh object? Is there a way to get the FLAME parameters as well?

**Comment by TimoBolkart** [comment]
VOCA outputs meshes in FLAME mesh topology. However, it does not directly output FLAME parameters but you can easily compute this using this code [TF_FLAME](https://github.com/TimoBolkart/TF_FLAME). The demo to fit the 3D model to registered 3D meshes should do the job

**Comment by jzf2101** [comment]
@tursmanor and I have tried to run [TF_FLAME/fit_3D_mesh.py](https://github.com/TimoBolkart/TF_FLAME/blob/master/fit_3D_mesh.py) on the mesh output of VOCA.  However, we find that there are notable differences in pose, specifically with regards to the mouth position.

The mesh on the left is the output of VOCA and the one on the right is the result of [fit_3D_mesh.py](https://github.com/TimoBolkart/TF_FLAME/blob/master/fit_3D_mesh.py)

![fitting-results](https://user-images.githubusercontent.com/1373035/69355359-a5183c00-0c4f-11ea-801e-a9d9768e556e.png)

Given the fact that the output of VOCA is already in FLAME topology, is there another way to get the FLAME parameters directly from the VOCA model without rerunning it through FLAME?

**Comment by TimoBolkart** [comment]
> The mesh on the left is the output of VOCA and the one on the right is the result of fit_3D_mesh.py

This looks not right, FLAME should be much better in fitting this mesh. Can you please provide this particular mesh to me?

> Given the fact that the output of VOCA is already in FLAME topology, is there another way to get the FLAME parameters directly from the VOCA model without rerunning it through FLAME?

VOCA outputs meshes in FLAME topology, but there is no way to directly go from a FLAME mesh to the model parameters without optimization.

**Comment by jzf2101** [comment]
File is below:

[00056.obj.zip](https://github.com/TimoBolkart/voca/files/3875677/00056.obj.zip)

We have attempted to vary the weight parameters in `TF_FLAME/fit_3D_mesh.py` to improve performance with little luck.  Increasing the parameter weights in  for `jaw_pose` by 8 orders of magnitude (1000) leads to a slightly more open mouth, which is still not close to the VOCA mesh.

![inc-jaw-pose-weight](https://user-images.githubusercontent.com/1373035/69356680-d8f46100-0c51-11ea-9c7b-06d6ab953662.png)

**Comment by TimoBolkart** [comment]
Thanks for pointing this out. This is actually a problem of the L-BFGS-B solver used in the TF_FLAME fitting. Weighting the data term higher, will give you a better result. Alternatively you could change the convergence parameters of the solver. Below, you can see your input mesh (left), a fitting based on the [Chumpy code](https://github.com/Rubikplayer/flame-fitting) (middle), and a fitting using TF_FLAME with higher weighted data term, and using BFGS instead of L-BFGS-B (right). They look much more similar compared to your fitting before. Just pull the TF_FLAME repository and you will get the changes.

![mesh_fitting](https://user-images.githubusercontent.com/26549953/69360002-06f59780-0c8a-11ea-9805-0e210b2b50f1.png)

>  Increasing the parameter weights in for jaw_pose by 8 orders of magnitude (1000) leads to a slightly more open mouth, which is still not close to the VOCA mesh.

The weights for shape, expression, neck_pose, jaw_pose, and eyeball_pose are actually weights of the regularizers. Increasing these weights leads to more regularization and hence it even looks more like the mean face.

**Comment by jzf2101** [comment]
Thank you !!!!
