### ISSUE TITLE
Any reason that VOCA does not output FLAME parameters?

### ISSUE THREAD

**Issue by bing-jian** [TimoBolkart/voca#26]
Hi Timo,

First thanks for sharing the code for VOCA, very impressive work.  I am wondering why  VOCA does not output FLAME parameters (at least expression parameters).  Can the current VOCA network be modified such that the model will output expression parameters?
 
"VOCA outputs meshes in FLAME mesh topology. However, it does not directly output FLAME parameters but you can easily compute this using this code [TF_FLAME](https://github.com/TimoBolkart/TF_FLAME). The demo to fit the 3D model to registered 3D meshes should do the job"

_Originally posted by @TimoBolkart in https://github.com/TimoBolkart/voca/issues/21#issuecomment-554553279_

**Comment by TimoBolkart** [comment]
Hi,
sure, alternatively one can directly output FLAME parameters (i.e. expression and jaw pose). However, we have tried this but ended up directly outputting vertex offsets due to performance reasons. Having just one trainable linear FC layer instead of a fixed FLAME layer as decoder significantly reduced the training time and produced favorable results.

**Comment by bing-jian** [comment]
Timo,  that makes sense.  Thanks for the explanation!

**Comment by kk66668** [comment]
Have you tryied add FLAME layer as decoder to train VOCA?
