### ISSUE TITLE
ValueError running README example

### ISSUE THREAD

**Issue by antonslutsky** [TimoBolkart/voca#27]
Hello,

I set up the project and tried running the example command:

python run_voca.py --tf_model_fname './model/gstep_52280.model' --ds_fname './ds_graph/output_graph.pb' --audio_fname './audio/test_sentence.wav' --template_fname './template/FLAME_sample.ply' --condition_idx 3 --out_path './animation_output'

The script runs for a while and terminates with the following error:
ValueError: Cannot feed value of shape (1, 254, 494) for Tensor 'deepspeech/input_node:0', which has shape '(1, 16, 19, 26)'

Am not sure if doing something wrong or if this is an issue, but would appreciate any advice.

Thank you,
Anton

**Comment by TimoBolkart** [comment]
Dear Anton,

this looks like a problem with DeepSpeech. How did you install DeepSpeech, and which version are you using?

Best,
Timo

**Comment by TimoBolkart** [comment]
Since there is no response, I assume the problem to be solved. 
If not, please try to install DeepSpeech as described (i.e. download the trained DeepSpeech model (v0.1.0) from Mozilla/DeepSpeech (i.e. deepspeech-0.1.0-models.tar.gz)). 
Trying to use any newer DeepSpeech model or installing DeepSpeech via pip install will cause an error as described by you.
