### ISSUE TITLE
DeepSpeech is Too Slow, Is there other possible features?

### ISSUE THREAD

**Issue by plmsmile** [TimoBolkart/voca#33]
DeepSpeech is too slow, So I want to try some other model features. Does this will influence the performance matter? Is there some possible features(models) those look like good?
Thank you very much~

**Comment by TimoBolkart** [comment]
DeepSpeech allows us to better generalize to new speech sequences despite having only limited amounts of training data. We did some experiments using MFCC or FBANK features instead but using DeepSpeech provided the best results. 

Since the training code is publicly available, you can just experiment with different speech features to see if this suffices your expectations in both, quality and speech.

**Comment by ulucsahin** [comment]
@zhangqijun And updates on this? I have the same issue. It only needs to run once in my code so wasting about 40 seconds for a small input is a big issue for me.

**Comment by kyuhyoung** [comment]
> Deepspeech uses TF as the framework. The test found that it seems to be very slow the first time in sess run, which consumes more than 40 seconds. When sess was run for the second time, deepspeech only took 0.4 seconds to get the result of bz205. Trying to figure out what went wrong the first time.

Anyway, what is bz205 ?
