### ISSUE TITLE
Audio/mesh alignment

### ISSUE THREAD

**Issue by tobyclh** [TimoBolkart/voca#5]
Hello, thank you for making this code available, this is some really awesome work.
I am looking at the data provided in the project page now, 
The mesh sequence for each sentence and the audio is not strictly aligned.
(i.e., the FPS calculated from # of mesh/sample size*sample rate are roughly 59~61)
Would you please elaborate on how can the audio is cropped or aligned with the video in the original capture/training process?
Thank you.

**Comment by TimoBolkart** [comment]
Hello, for training, we first convert the raw audio to overlapping windows. This pre-processing is shown in utils/audio_handler.py. The training then uses the processed_audio audio windows rather than the raw audio. Due to rounding issues it however happens, that the number of audio windows and the number of geometry frames slightly differ. In this case, we only consider min(num_data_frames, num_audio_frames) as the last frame of the sequence.

**Comment by zhipeng-fan** [comment]
Hi, could you please tell me what is the loss look like when your training terminates? It would be the best if you could share the number for the position loss and the velocity loss separately.

**Comment by tobyclh** [comment]
@TimoBolkart 
Thank you for the response, I have successfully computed the frames!

@zhipeng-fan 
I am not trying to reproduce what the paper do, so I don't imagine what I do would give you much insight.
